<htmlform>
	<!-- Autogenerated example form  (template from 01-Nov-2010 -->
	<macros>
		paperFormId = (Fill this in)
		headerColor =#009d8e
		fontOnHeaderColor = white
	</macros>

	<style>
		.section {
			border: 1px solid $headerColor;
			padding: 2px;
			text-align: left;
			margin-bottom: 1em;
		}
		.sectionHeader {
			background-color: $headerColor;
			color: $fontOnHeaderColor;
			display: block;
			padding: 2px;
			font-weight: bold;
		}
		table.baseline-aligned td {
			vertical-align: baseline;
		}
	</style>
	<!-- Autogenerated example form  (template from 01-Nov-2010 -->
	<table width="95%" border="0">
	  <tr>
	    <td colspan="3" align="center"><h2>COMPREHENSIVE CARE CLINIC PATIENT BLUE CARD</h2></td>
      </tr>
	  <tr>
	    <td width="49%"><section headerLabel="Patient Profile"><table width="100%" border="0">
	      <tr>
	        <td colspan="4">Unique Patient No: <patient field="identifier"/></td>
	        </tr>
	      <tr>
	        <td colspan="2">Patient's Name</td>
	        <td colspan="2">DOB</td>
	        </tr>
	      <tr>
	        <td width="47%"></td>
	        <td width="3%"><patient field="name"/></td>
	        <td width="46%"></td>
	        <td width="4%"><patient field="birthDateOrAge" /></td>
          </tr>
	      <tr>
	        <td>Sex:</td>
	        <td><patient field="gender"/></td>
	        <td>Patient Address:</td>
	        <td></td>
	        </tr>
	      <tr>
	        <td>Tel Contact:</td>
	        <td></td>
	        <td><span class="textalign_right">District</span>:</td>
	        <td><obs conceptId="161564AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>Location:</td>
	        <td><patient field="identifierLocation" /> </td>
	        <td>Sub-Location:</td>
	        <td></td>
	        </tr>
	      <tr>
	        <td>Nearest School:</td>
	        <td></td>
	        <td><span class="textalign_right">Nearest Centre:</span></td>
	        <td><obs conceptId="1811AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>Marital Status:</td>
	        <td><obs conceptId="1054"/></td>
	        <td></td>
	        <td></td>
	        </tr>
        </table>
	    </section>
        
        <section headerLabel="Treatment Supporter"><table width="100%" border="0">
	      <tr>
	        <td width="47%">Name:</td>
	        <td width="3%"><obs conceptId="160638AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        <td width="46%">Relatioship:</td>
	        <td width="4%"><obs conceptId="160640AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>Postal Address:</td>
	        <td><obs conceptId="160641AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        <td><span class="textalign_right">Telephone</span>:</td>
	        <td><obs conceptId="160642AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      </table>
	    </section>
        <section headerLabel="Patient Source"><table width="100%" border="0">
	      <tr>
	        <td width="47%">Entry Point::</td>
	        <td colspan="3"><obs conceptId="160540AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>Transfer in Date:</td>
	        <td width="3%"><obs conceptId="160534AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        <td width="46%"><span class="textalign_right">From District</span>:</td>
	        <td width="4%"><obs conceptId="161551AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>Facility</td>
	        <td><obs conceptId="161550AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        <td><span class="textalign_right">Date started ART: </span></td>
	        <td><obs conceptId="159599AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        </tr>
	      </table>
	    </section>
        <section headerLabel="ART History"><table width="100%" border="0">
	      <tr>
	        <td width="47%">Previous on ARVs:</td>
	        <td colspan="3"> <obs conceptId="160533AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" style="no_yes_dropdown"></obs></td>
	        </tr>
	      <tr>
	        <td>Date Confirmed HIV Positive:</td>
	        <td width="3%"><obs conceptId="160554AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        <td width="46%">Where:</td>
	        <td width="4%"><obs conceptId="159936AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        </tr>
	      <tr>
	        <td>Date Enrolled HIV Care:</td>
	        <td><obs conceptId="160555AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        <td><span class="textalign_right">Date started ART: </span></td>
	        <td><obs conceptId="159599AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        </tr>
	      <tr>
	        <td>WHO Stage:</td>
	        <td><obs conceptId="160553AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        <td>Any known drug Allergies:</td>
	        <td></td>
	        </tr>
	      </table>
	    </section>
        </td>
	    <td width="1%"></td>
	    <td width="50%" valign="top"><section headerLabel="HIV Status of Family Memeber"><table width="100%" border="0">
	      <tr>
	        <td width="31%">Name:</td>
	        <td width="21%"><obs conceptId="160750AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        <td width="22%">Age:</td>
	        <td width="26%"><obs conceptId="160751AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>Relationship:</td>
	        <td><obs conceptId="1560AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        <td>HIV(P/NDK):</td>
	        <td><obs conceptId="1169AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>In Care?</td>
	        <td><obs conceptId="160749AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        <td>CC No:</td>
	        <td><obs conceptId="160752AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td></td>
	        <td></td>
	        <td></td>
	        <td></td>
	        </tr>
        </table>
	    </section>
        <section headerLabel="ART Therapy"><table width="100%" border="0">
	      <tr>
	        <td width="31%">Date Medically Elligible:</td>
	        <td colspan="3"><obs conceptId="162227AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>Elligible Through:</td>
	        <td colspan="3"> <obs conceptId="162225AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>Date Started on 1st Line:</td>
	        <td colspan="3"><obs conceptId="159599AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td>Regimen:</td>
	        <td colspan="3"><obs conceptId="162240AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td colspan="4">At Start of ART</td>
	        </tr>
	      <tr>
	        <td><span class="textalign_right">Weight (Kgs):</span></td>
	        <td><obs conceptId="5089AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        <td><span class="textalign_right">Height (cms):</span></td>
	        <td><obs conceptId="5090AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
	        </tr>
	      <tr>
	        <td><span class="textalign_right">BMI (Adults):</span></td>
	        <td><obs conceptId="1342AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        <td><span class="textalign_right">WHO Stage:</span></td>
	        <td><obs conceptId="5356AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"></obs></td>
	        </tr>
	      <tr>
	        <td colspan="4"><em>Substitution of ARVs within 1st Line Regimens</em></td>
	        </tr>
	      <tr>
	        <td colspan="4"><table width="100%" align="center" class="display maincopy">
                 <th width="19%">Dates</th>
                 <th width="30%">Regimens</th>
                 <th width="29%">Reason(s)</th>
                 
                 <tr>
         <td><obs conceptId="159599"/></td>
        <td><obs conceptId="162240"/></td>
        <td><obs conceptId="160562"/></td>
        
        </tr>
             </table></td>
	        </tr>
	      <tr>
	        <td colspan="4"><em>Switch to 2nd Line (Substitute within 2nd Line)</em></td>
	        </tr>
	      <tr>
	        <td colspan="4"><table width="100%" align="center" class="display maincopy">
               

                 <th width="19%">Dates</th>
                 <th width="30%">Regimens</th>
                 <th width="29%">Reason(s)</th>
                 
                 <tr>
         <td><obs conceptId="159599"/></td>
        <td><obs conceptId="162240"/></td>
        <td><obs conceptId="160568"/></td>
        </tr>
      </table></td>
	        </tr>
	      <tr>
	        <td></td>
	        <td width="21%"></td>
	        <td width="20%"></td>
	        <td width="28%"></td>
	        </tr>
        </table>
	    </section>
        
        <section headerLabel="Transfer Out and Death"><table width="100%" class="display maincopy">
               

                 <th>*Date</th>
                
                 <th>Where</th>
                <th>Reason</th>
                 <tr>
         <td><obs conceptId="160649AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
        <td><obs conceptId="159495AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"/></td>
        <td></td>
        </tr>
             </table>
	    </section>
        
        <section headerLabel="ART Treatment Interruption"><table width="100%" class="display maincopy">
               

                 <th>Date</th>
                 <th>Reason for Interruption</th>
                 <th>Date Restarted</th>
                 
                 <th></th>
                   
     <tr>
         <td><obs conceptId="160739"/></td>
        <td><obs conceptId="1252"/></td>
        <td><obs conceptId="159599"/></td>
      </tr>
             </table>
	    </section>
        </td>
	    <td width="0%"></td>
	    <td width="0%"></td>
      </tr>
	  <tr>
	    <td></td>
	    <td></td>
	    <td></td>
      </tr>
    </table>
	</htmlform>
